name: 'Setup LocalStack'
description: 'Sets up LocalStack CLI in your GitHub Actions workflow.'
author: 'LocalStack Team'

branding:
  icon: 'code'
  color: 'white'

runs:
  using: "composite"
  steps:
    - 
      run: |
        pip install awscli-local
      shell: bash
