name: 'tflocal deploy'
description: 'Deploys terraform on LocalStack.'
author: 'LocalStack Team'

branding:
  icon: 'code'
  color: 'white'

inputs:
  path:
    description: 'Path to terraform directory'
    required: false
    default: 'terraform'

runs:
  using: "composite"
  steps:
    - id: tf-init
      working-directory: ${{ inputs.path }}
      run: |
        tflocal init
      shell: bash

    - id: tf-deploy
      working-directory: ${{ inputs.path }}
      run: |
        tflocal apply --auto-approve
      shell: bash

    - id: pr-comment
      uses: actions/github-script@v3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '![LocalStack](https://img.shields.io/badge/LocalStack-Validated-blue) Terraform files deployed successfully on LocalStack.'
          })
      if: always()
