name: 'tflocal deploy'
description: 'Deploys terraform on LocalStack.'
author: 'LocalStack Team'

branding:
  icon: 'code'
  color: 'white'

inputs:
  path:
    description: 'Path to terraform directory'
    required: false
    default: 'terraform'
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - id: tf-init
      working-directory: ${{ inputs.path }}
      run: |
        tflocal init
      shell: bash

    - id: tf-deploy
      working-directory: ${{ inputs.path }}
      run: |
        tflocal apply --auto-approve
      shell: bash
      continue-on-error: true

    - id: pr-comment
      uses: actions/github-script@v4
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const issue_number = context.issue.number;
          const repo = context.repo;
          github.rest.issues.createComment({
            owner: repo.owner,
            repo: repo.repo,
            issue_number: issue_number,
            body: "It worked! :tada:"
          });
      if: ${{ github.event_name == 'pull_request' }}
