name: 'tflocal deploy'
description: 'Deploys terraform on LocalStack.'
author: 'LocalStack Team'

branding:
  icon: 'code'
  color: 'white'

inputs:
  path:
    description: 'Path to terraform directory'
    required: false
    default: 'terraform'
  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - id: tf-init
      working-directory: ${{ inputs.path }}
      run: |
        tflocal init
      shell: bash

    - id: tf-deploy
      working-directory: ${{ inputs.path }}
      run: |
        tflocal apply --auto-approve
      shell: bash
      continue-on-error: true

    - id: pr-comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ inputs.github-token }}
        script: |
          const tfDeploymentStatus = "${{ steps.tf-deploy.outcome }}"
          let message
          if (tfDeploymentStatus === 'success') {
            message = `
            Terraform Deployment Completed on **LocalStack**.

            **Deployment Status**

            | Deployment Status | ![LocalStack](https://img.shields.io/badge/LocalStack-Deployed-green) |
            |-------------------|-----------------------------------------------------------------------|
            | Notes             | Terraform files deployed successfully on LocalStack.                  |
            `
          } else if (tfDeploymentStatus === 'failure') {
            message = `
            Terraform Deployment Completed on **LocalStack**.

            **Deployment Status**
            
            | Deployment Status | ![LocalStack](https://img.shields.io/badge/LocalStack-Failed-red) |
            |-------------------|-------------------------------------------------------------------|
            | Notes             | Terraform files could not deploy successfully on LocalStack.      |
            `
          } else {
            message = `
            Terraform Deployment Completed on **LocalStack**.

            **Deployment Status**
            
            | Deployment Status | ![LocalStack](https://img.shields.io/badge/LocalStack-Error-yellow) |
            |-------------------|---------------------------------------------------------------------|
            | Notes             | Unable to determine deployment status.                              |
            `
          }

          const issue_number = context.issue.number;
          const repo = context.repo;
          await github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: message
          })
      if: ${{ github.event_name == 'pull_request' }}
