name: 'tflocal deploy'
description: 'Deploys terraform on LocalStack.'
author: 'LocalStack Team'

branding:
  icon: 'code'
  color: 'white'

inputs:
  path:
    description: 'Path to terraform directory'
    required: false
    default: 'terraform'

runs:
  using: "composite"
  steps:
    - id: tf-init
      working-directory: ${{ inputs.path }}
      run: |
        tflocal init
      shell: bash

    - id: tf-plan
      working-directory: ${{ inputs.path }}
      run: |
        tflocal apply --auto-approve
      shell: bash
