name: test-setup-localstack
on: [ push, pull_request ]

jobs:
  localstack-action-test:
    name: 'Test Setup LocalStack GitHub Action'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup awslocal
        uses: ./setup-local-tools
        with:
          awslocal: 'true'

      - name: Test awslocal version
        run: |
          awslocal --version

      - name: Setup terraform
        uses: ./setup-local-tools
        with:
          terraform: 'true'
          terraform-version: '0.14.7'

      - name: Test terraform version
        run: |
          terraform --version
